<?php

$catalogo_coroas = [
    'Conjunto B Luxo Colorido'      => ['preco' => 1500.00, 'tempo_producao' => 60],
    'Conjunto A Luxo'               => ['preco' => 2970.00, 'tempo_producao' => 90],
    'Conjunto B Luxo'               => ['preco' => 1700.00, 'tempo_producao' => 60],
    'Conjunto B Semi Luxo Colorido' => ['preco' => 1500.00, 'tempo_producao' => 60],
    'Conjunto Las Vegas'            => ['preco' => 3850.00, 'tempo_producao' => 120],
    'Conjunto Lisboa'               => ['preco' => 7950.00, 'tempo_producao' => 180],
    'Conjunto New York'             => ['preco' => 2800.00, 'tempo_producao' => 90],
    'Conjunto Ouro Branco'          => ['preco' => 1850.00, 'tempo_producao' => 60],
    'Conjunto São Paulo'            => ['preco' => 7300.00, 'tempo_producao' => 180],
    'Conjunto Sidney'               => ['preco' => 10550.00, 'tempo_producao' => 240],
    'Conjunto Tókio'                => ['preco' => 2420.00, 'tempo_producao' => 90],
    'Conjunto Vip III'              => ['preco' => 9500.00, 'tempo_producao' => 200],
    'Coroa A Vip I'                 => ['preco' => 4850.00, 'tempo_producao' => 120],
    'Coroa A Vip II'                => ['preco' => 4850.00, 'tempo_producao' => 120],
    'Coração Cheio'                 => ['preco' => 1100.00, 'tempo_producao' => 45],
    'Coração Vazado Vermelho'       => ['preco' => 1320.00, 'tempo_producao' => 45],
    'Coração Vazado Branco'         => ['preco' => 1320.00, 'tempo_producao' => 45],
    'Corbélia'                      => ['preco' => 900.00,  'tempo_producao' => 30],
    'Arranjo Estocolmo'             => ['preco' => 800.00,  'tempo_producao' => 30],
    'Coroa A Luxo Branca'           => ['preco' => 1150.00, 'tempo_producao' => 45],
    'Coroa A Luxo Colorida'         => ['preco' => 1300.00, 'tempo_producao' => 45],
    'Coroa B Luxo Branca'           => ['preco' => 660.00,  'tempo_producao' => 30],
    'Guirlanda Luxo Tons Claros'    => ['preco' => 1100.00, 'tempo_producao' => 45],
    'Coroa B Semi Luxo'             => ['preco' => 495.00,  'tempo_producao' => 30],
    'Coroa B Simples'               => ['preco' => 385.00,  'tempo_producao' => 20],
    'Coroa Dubai'                   => ['preco' => 1430.00, 'tempo_producao' => 60],
    'Coroa Tókio'                   => ['preco' => 1450.00, 'tempo_producao' => 60],
    'Coroa Sidney'                  => ['preco' => 4950.00, 'tempo_producao' => 120],
    'Coroa Havaiana'                => ['preco' => 3850.00, 'tempo_producao' => 120],
];
